### PR TITLE
LPS-109998, LPS-111225 Remove alloyeditor from Announcements

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @austinchiang, in this pull: 

1. The title field is an input instead of an alloyeditor, and has been renamed from "titleEditor" to "title"

2. The content field is CKEditor 

Please check if there are poshi tests that needs to be updated. 

Thanks a lot!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @austinchiang,

@ambrinchaudhary has completely removed the `announcements-editor-configuration` module since it is no longer needed. 

Is there anything (maybe release related) that has to be changed too?

Thanks!

**Comment by 4lejandrito** [comment]
`git grep announcements-editor-configuration` yields one result in `modules/modules.properties`. Maybe we need to remove that too.

**Comment by austinchiang** [comment]
Hey @4lejandrito I'm not too clear if there are release files that need to be changed if that module is removed. Maybe @jpince will know.

**Comment by Hanlf** [comment]
Cannot add an announcement on the Windows system: Input fields are not editable.
Reproduced on:
Tomcat 9.0.33 + MySQL 5.7. Portal + **Windows 10**.
Can not be reproduced on:
Tomcat 9.0.33 + MySQL 5.7. Portal + **Ubuntu**.
Tomcat 9.0.33 + MySQL 5.7. Portal + **CentOS**. (CI tests)

annoucements

And error throws on the console:
```
2020-04-03 07:33:44.982 ERROR [http-nio-8080-exec-6][StripFilter:62] java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://localhost:8080/web/guest/announcements-page
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://localhost:8080/web/guest/announcements-page
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:73)
        at com.google.javascript.jscomp.SourceMapResolver.extractSourceMap(SourceMapResolver.java:53)
        at com.google.javascript.jscomp.JsAst.parse(JsAst.java:168)
        at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:55)
        at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:134)
        at com.google.javascript.jscomp.Compiler.hoistIfExtern(Compiler.java:2076)
        at com.google.javascript.jscomp.Compiler.hoistExterns(Compiler.java:2062)
        at com.google.javascript.jscomp.Compiler.findDependenciesFromEntryPoints(Compiler.java:1944)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1787)
        at com.google.javascript.jscomp.Compiler.parseForCompilationInternal(Compiler.java:981)
        at com.google.javascript.jscomp.Compiler.access$300(Compiler.java:101)
        at com.google.javascript.jscomp.Compiler$6.call(Compiler.java:963)
        at com.google.javascript.jscomp.Compiler$6.call(Compiler.java:960)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:128)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:861)
        at com.google.javascript.jscomp.Compiler.parseForCompilation(Compiler.java:959)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:712)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:689)
        at com.frontend.js.minifier.GoogleJavaScriptMinifier.compress(GoogleJavaScriptMinifier.java:68)
        at com.liferay.portal.minifier.MinifierUtil._minifyJavaScript(MinifierUtil.java:109)
        at com.liferay.portal.minifier.MinifierUtil.minifyJavaScript(MinifierUtil.java:47)
        at com.liferay.portal.servlet.filters.strip.StripFilter.processJavaScript(StripFilter.java:526)
        at com.liferay.portal.servlet.filters.strip.StripFilter.strip(StripFilter.java:673)
        at com.liferay.portal.servlet.filters.strip.StripFilter.processFilter(StripFilter.java:384)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:368)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:58)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:340)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:87)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.processFilter(AutoLoginFilter.java:264)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:250)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
        at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:183)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at com.liferay.portal.servlet.filters.urlrewrite.UrlRewriteFilter.processFilter(UrlRewriteFilter.java:65)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by austinchiang** [comment]
@ambrinchaudhary can you please take a look? Thx

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary can you please take a look? Thx

@julien will do, I don't have a windows machine :-(

**Comment by julien** [comment]
@ambrinchaudhary I actually don't have a Windows machine, I use VirtualBox (you can get a Windows 10 VM [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)) 

@Hanlf I assumed this was happening on IE11 but I'll try with other browsers in a bit.

Concerning this error, this is what I see on IE11 - Windows 10 (this is in Virtual Box)

1. Upon loading the page, I get a JS error, but no exactly the same one described: 

screenshot

*This has to do with one of the dependencies not being loaded properly (didn't check why that was happening ATM)*

Tomcat's log however is "clean" in my case 

screenshot_3

2. After the page finishes loading (which does take it's time on IE11 in VBox) I can write in the text fields

screenshot_1

3. Clicking on save also works for me:

screenshot_2

Will try with Chrome

**Comment by julien** [comment]
@Hanlf wasn't seing your screenshot in this PR, will try with the announcements **Widget**

**Comment by julien** [comment]
This is what I see with the Announcements Widget added to the Home page:

1. Same loader error as before (but I noticed it happens before adding the Announcements Widget to the page)

screenshot_4

2. After everything is loaded, I can see CKEditor and type into the text fields

screenshot_5

3. After saving the announcement, I can see it on the home page

screenshot_6

**Comment by julien** [comment]
This is what it looks like on Chrome

screenshot_10

*Notice that in this screenshot we don't see the loader error as on IE, even though I think it's not related to this change*

And this can also be saved

screenshot_11

**Comment by julien** [comment]
And here's what it looks like on Firefox

screenshot_12

*For some reason, we get a warning on Firefox that we don't get on IE or Chrome*

That doesn't prevent the widget to be used 

screenshot_13

And we can also see that it was saved correctly

screenshot_14

**Comment by julien** [comment]
The last thing  I wanted to add is that while testing these 3 browsers nothing was logged in Tomcat's log, so I don't see [this](https://github.com/austinchiang/liferay-portal/pull/745#issuecomment-608284547) error either.

**Comment by jpince** [comment]
@ambrinchaudhary @4lejandrito @austinchiang I don't remember running into issues when removing modules.  Just make sure to run a full SF `ant format-source-all '-Dskip.npm=true'`.  I'm curious to know if it automatically removes this. If not, please let me know, because I think it should.
> `git grep announcements-editor-configuration` yields one result in `modules/modules.properties`. Maybe we need to remove that too.

Let me know if any other test failures come up after the merge to upstream so I can be aware for the future :)

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/754<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/fe289a161852~3...fe289a161852)

**Comment by Hanlf** [comment]
Hi @ambrinchaudhary  and @julien ,

Thanks for looking into it.

I rebuild a bundle with these commits at the master head, no issue now: able to add announcements and no error throws on the console.
The InvalidPathException should be not related to this pull, I found that other people also encountered it: see https://issues.liferay.com/browse/LPS-106683.

cc/ @austinchiang

**Pull request closed without merging**
