### PR TITLE
master-qa-126104

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-126104

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1408

**Pull request closed without merging**
