### PR TITLE
LPS-77252 Tests for MBCategoryService

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @austinchiang 

This pull changes the list view of Message Boards in live and it uses 2 different search containers (one for categories and for threads) instead of just one. This solves a UX issue when there are tons of categories and it makes it very difficult to find the first thread. This is important in sites. With this fix we have 2 different paginations, one for categories and one for threads and both are displayed, no matter how many categories are.

In Administration we didn't apply this view because we think that in order to administer, the existing view is better.

Could you please check (and fix if necessary) any functional test broken?

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @patriciajeanperez

**Comment by sergiogonzalez** [comment]
cc/ @ngaskill this changes the current behaviour and UI for Message Boards and I think it might be worth mentioning in the user docs.

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
Hey @sergiogonzalez, seems like the `Statistics` and `Banned Users` navtabs are missing from site administration. Since this is only causing one test to fail, I'll go ahead and push this to BChan and file a ticket in retrospect for this issue.

**Pull request closed without merging**
