### PR TITLE
LPS-136825, LPS-136826, LPS-136917, LPS-136918, LPS-143286 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-136825
https://issues.liferay.com/browse/LPS-136826
https://issues.liferay.com/browse/LPS-136917
https://issues.liferay.com/browse/LPS-136918
https://issues.liferay.com/browse/LPS-143286

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Good work @LeandroTravassos !

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
