### PR TITLE
LPS-126827, LPS-126842, LPS-126854

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-126827
https://issues.liferay.com/browse/LPS-126842
https://issues.liferay.com/browse/LPS-126854

### CODE REVIEW

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1457<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/b39bfa04ef8a~2...b39bfa04ef8a)

**Comment by austinchiang** [comment]
@joshchong I think some interns probably rebased off each other so they were using the same new paths which you removed in this pull. But you wouldn't have noticed this unless you were reviewing all of the pulls 👀

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/98414<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/b39bfa04ef8a~2...b39bfa04ef8a)

**Comment by joshchong** [comment]
@austinchiang thanks for catching that!

**Pull request closed without merging**
