### PR TITLE
master-lps-132324

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-132604
https://issues.liferay.com/browse/LPS-132563
https://issues.liferay.com/browse/LPS-132606
https://issues.liferay.com/browse/LPS-132662
https://issues.liferay.com/browse/LPS-132324

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Good work @liuxingye !

**Comment by liuxingye** [comment]
Thank you for the changes @austinchiang

**Pull request closed without merging**
