### PR TITLE
LPS-166731 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-166731

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:lima-db-partition

**Comment by Jeremy-Ch** [comment]
ci:test:lima-db-partition

**Comment by Jeremy-Ch** [comment]
The results look like have some issues, only including the upgrade tests. I will close this pull request and resend it.

**Pull request closed without merging**
