### PR TITLE
LPS-129431, LPS-129432, LPS-129437, LRQA-66306 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-129431
https://issues.liferay.com/browse/LPS-129432
https://issues.liferay.com/browse/LPS-129437
https://issues.liferay.com/browse/LRQA-66306

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The SF failure about build.properties is not related to my commits, also occurs on upstream: https://testray.liferay.com/zh/home/-/testray/case_results/1522880188

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1699<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/6b737672b54d~1...6b737672b54d)

**Pull request closed without merging**
