### PR TITLE
LPS-136846, LPS-136847, LPS-136850 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-136846
https://issues.liferay.com/browse/LPS-136847
https://issues.liferay.com/browse/LPS-136850

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Resent here https://github.com/liferay-lima/liferay-portal/pull/2557

**Comment by austinchiang** [comment]
Resent here https://github.com/liferay-lima/liferay-portal/pull/2557

**Pull request closed without merging**
