### PR TITLE
LPS-103619 Add tests.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:documents

**Comment by Hanlf** [comment]
ci:test:depot

**Comment by austinchiang** [comment]
Closing pull. There were issues with the item selector restricting what kinds of documents could be uploaded for and thus selected as file shortcuts.

**Pull request closed without merging**
