### PR TITLE
LPS-156478 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-156478

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
Pushed to Lima.
https://github.com/liferay-lima/liferay-portal/pull/3326

**Pull request closed without merging**
