### PR TITLE
Master | LPS-101039, LPS-114328

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-101039
https://issues.liferay.com/browse/LPS-114328

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/467<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/e78e1666f5f4~1...e78e1666f5f4)

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/468<br></br>

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/469<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/d27e0746e5b3~2...d27e0746e5b3)

**Pull request closed without merging**
