### PR TITLE
LPS-154457, LPS-154453, LPS-154445, LPS-154446, LPS-154454, LPS-154458 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-154457
https://issues.liferay.com/browse/LPS-154453
https://issues.liferay.com/browse/LPS-154445
https://issues.liferay.com/browse/LPS-154446
https://issues.liferay.com/browse/LPS-154454
https://issues.liferay.com/browse/LPS-154458

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Good work @liuxingye

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
