### PR TITLE
LRQA-35294 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-35294

### CODE REVIEW

**Comment by pcwhite** [comment]
@anthony-chu

**Comment by austinchiang** [comment]
@pcwhite Does this change need to be applied to 7.0.x as well?

**Comment by austinchiang** [comment]
No test changes needed

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51976

@pcwhite  See my comments to BChan since I am only submitting on one branch.

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Pull request closed without merging**
