### PR TITLE
LPS-110014 KB (remove AlloyEditor)

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[LPS-110014](https://issues.liferay.com/browse/LPS-110014) - Replace AlloyEditor in Title field in Knowledge Base Templates
[LPS-110598](https://issues.liferay.com/browse/LPS-110598) - Fields identification in Knowledge Base)

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Hey Austin, I have tested this poshi tests: 
- **CPKnowledgebase#AddKBArticlesViaKBAdmin**: It works fine for me in local

- **CPKnowledgebase#AddTemplateCP**: Seems to be an error in poshi test and have fixed in the last commit (thanks to Manoel)

- **PGKnowledgebasedisplay#EditKBArticle**: I haven't discovered what is failing. This is the error I get: 
Expected text "Knowledge Base Article Content Edit" does not match actual text (case insensitive) "Knowledge Base Article Content EditKnowledge Base Article Content" at "//div[contains(@class,'kb-entity-body')]//p"
Seems that while editing an kb article in the tests, instead of replacing the content is appending it. Manoel thinks that maybe a clean is needed before doing that...

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/724<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/b7e08e0bb3fb~1...b7e08e0bb3fb)

**Comment by austinchiang** [comment]
Hey @ambrinchaudhary thanks for the catches! For the last test, it is because we are using the `Keypress` function which appends like you mentioned. I've changed it to the `Type` function, which replaces, for knowledge base edits. Thanks!

**Pull request closed without merging**
