### PR TITLE
LPS-127173, et. al | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-127168
https://issues.liferay.com/browse/LPS-127169
https://issues.liferay.com/browse/LPS-126829
https://issues.liferay.com/browse/LPS-127820
https://issues.liferay.com/browse/LPS-126848
https://issues.liferay.com/browse/LPS-127169

Beck:
https://issues.liferay.com/browse/LPS-127167
https://issues.liferay.com/browse/LPS-127166
https://issues.liferay.com/browse/LPS-122814
https://issues.liferay.com/browse/LPS-127172

Site Staging(From Jeremy and Yvonne):
https://issues.liferay.com/browse/LPS-127173

Add DE test for  the image field:
https://issues.liferay.com/browse/LPS-126865

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1470<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/6c7c99038875~1...6c7c99038875)

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Pull request closed without merging**
