### PR TITLE
LPS-100926  Getting clientId, clientSecret and refreshToken from PropsUtil

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test:backend

**Pull request closed without merging**
