### PR TITLE
master-lps-129209

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-129209

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Hey @Jeremy-Ch can you rebase and resend this? Thx

**Comment by Jeremy-Ch** [comment]
Hey @austinchiang See https://github.com/austinchiang/liferay-portal/pull/1089

**Pull request closed without merging**
