### PR TITLE
LPS-141201, LPS-143747, LPS-143740 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-141201
https://issues.liferay.com/browse/LPS-143747
https://issues.liferay.com/browse/LPS-143740

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Pull request closed without merging**
