### PR TITLE
LPS-126885... | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-126885
https://issues.liferay.com/browse/LPS-126796
https://issues.liferay.com/browse/LPS-126883
https://issues.liferay.com/browse/LPS-126910
https://issues.liferay.com/browse/LPS-126891
https://issues.liferay.com/browse/LPS-126886
https://issues.liferay.com/browse/LPS-126903

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1441<br></br>

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/98332<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/3276018408fa~3...3276018408fa)

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/98333<br></br>

**Pull request closed without merging**
