### PR TITLE
master-lps-136790

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-136790
https://issues.liferay.com/browse/LPS-136791
https://issues.liferay.com/browse/LPS-136793
https://issues.liferay.com/browse/LPS-136794
https://issues.liferay.com/browse/LPS-136795
https://issues.liferay.com/browse/LPS-136796

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Nice job @Jeremy-Ch

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
