### PR TITLE
7.0.x-qa-29127

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-29127

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
Changed some test properties and resent here: https://github.com/austinchiang/liferay-portal/pull/56

**Pull request closed without merging**
