### PR TITLE
master-lps-127159

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-127168
https://issues.liferay.com/browse/LPS-127169

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1463

**Comment by Jeremy-Ch** [comment]
See #954

**Pull request closed without merging**
