### PR TITLE
master-lrqa-58691

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-58691
https://issues.liferay.com/browse/LRQA-58762
https://issues.liferay.com/browse/LRQA-58760

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/803<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/ed66568fbd2e~2...ed66568fbd2e)

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/75<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/ed66568fbd2e~2...ed66568fbd2e)

**Pull request closed without merging**
