### PR TITLE
LRQA-38436 | master

### PR DESCRIPTION
**Pull request by timpak**
https://issues.liferay.com/browse/LRQA-38436

### CODE REVIEW

**Comment by austinchiang** [comment]
Hey @timpak , please make sure to include the LRQA # in your commit. Thanks!

**Comment by timpak** [comment]
LRQA # is now included in the commit message.

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55355

**Pull request closed without merging**
