### PR TITLE
LPS-100926 Set http non proxy hosts to bypass dummy proxy (review required)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LPS-100926

@austinchiang @4lejandrito
I've tried setting the proxy directly in the integration test via system properties but it didn't work, so I used Hashi's workaround instead:
https://github.com/austinchiang/liferay-portal/pull/513/commits/a965dae2987fe3f12bad0c5061eeab7884ff3e79

It will be up to you to decide whether Hashi's workaround is a better approach versus creating a new batch (Shuyang's suggestion) that turns dummy proxy off to group current and future tests that require direct connections together, the new batch will need to apply the following but in the new batch (Note: this commit turns dummy proxy off for all existing integration tests which Shuyang said should be avoided):
https://github.com/yichenroy/liferay-portal/pull/170/commits/ce09ce26625850c3d7061a8d4af3c8b81ff50abf

I squashed some commits into one so it's easier for backporting if needed:
https://github.com/austinchiang/liferay-portal/pull/513/commits/90ba356147decab1f644aa783aa49aab039a536f

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:onlineediting

**Comment by 4lejandrito** [comment]
Hi @yichenroy,

Thanks so much for following up on this. 

I'll be happy with whatever you guys decide when @austinchiang is back in the office. I can't be of much help on this one.

Regards

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by austinchiang** [comment]
Let's go with Hashi's workaround. I don't think we have a need to create a new batch for coherency right now, but we can explore Shuyang's suggestion more if it comes up in the future.

**Comment by austinchiang** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
