### PR TITLE
master-qa-48723

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-48739

### CODE REVIEW

**Comment by melodywu** [comment]
test:ci:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72737

**Pull request closed without merging**
