### PR TITLE
LPS-111356 Use CKeditor instead of Alloyeditor in wiki

### PR DESCRIPTION
**Pull request by julien**
In https://issues.liferay.com/browse/LPS-110019, AlloyEditor was
replaced with CKEditor in wiki but in an incorrect manner and
caused https://issues.liferay.com/browse/LPS-111356.

The intent here is still to replace AlloyEditor with CKEditor in wiki
but this time the configuration classes have been modified.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hi @julien 
I corrected that in https://github.com/austinchiang/liferay-portal/pull/744. Furthermore, the *ConfigContributors.java must not be changes, it applies only for AlloyEditor and they are correct. 
Did this get into master? How? It is still in review...

I would suggest to close this PR as the fixes will be sent in https://github.com/austinchiang/liferay-portal/pull/744

**Comment by john-co** [comment]
Hi @ambrinchaudhary, I think there was a miscommunication. I created a technical task ticket since this issue was discovered while analyzing the working PR associated with https://issues.liferay.com/browse/LPS-111251. I didn't know you were going to fix the issue at the time so I had assigned it to @julien. We'll close this out, thanks!

**Comment by john-co** [comment]
ci:close

**Comment by ambrinchaudhary** [comment]
no worries @john-co, I get it since this PR has been in my queue for several days ago... sorry!

**Pull request closed without merging**
