### PR TITLE
master-lps-127167

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-127168
https://issues.liferay.com/browse/LPS-127169
https://issues.liferay.com/browse/LPS-126829
https://issues.liferay.com/browse/LPS-127820
https://issues.liferay.com/browse/LPS-126848
https://issues.liferay.com/browse/LPS-127169
https://issues.liferay.com/browse/LPS-127167
https://issues.liferay.com/browse/LPS-127166

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Close this pull, I will resend it with Jeremy and my commits together.

**Comment by Hanlf** [comment]
ci:close

**Comment by liuxingye** [comment]
see https://github.com/austinchiang/liferay-portal/pull/954

**Pull request closed without merging**
