### PR TITLE
LRQA-35054 master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-35054

### CODE REVIEW

**Comment by pcwhite** [comment]
@anthonychu

**Comment by pcwhite** [comment]
@anthony-chu

**Comment by austinchiang** [comment]
@pcwhite Please update your commit message to reflect your logical change. See https://github.com/liferay/liferay-qa-ee/blob/liferay-qa-docs/tutorials/training/04-auto-analysis/pages/16-automation-test-commit-standards.markdown.

**Comment by pcwhite** [comment]
@austinchiang @anthony-chu commit message updated!

**Comment by austinchiang** [comment]
Just started reviewing :)

**Comment by austinchiang** [comment]
No test changes needed :)

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51749

**Pull request closed without merging**
