### PR TITLE
LPS-111475 KB friendlyUrl

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:knowledgebase

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/austinchiang/liferay-portal/pull/747

**Pull request closed without merging**
