### PR TITLE
LRQA-38910 | master

### PR DESCRIPTION
**Pull request by timpak**
https://issues.liferay.com/browse/LRQA-38910

### CODE REVIEW

**Comment by austinchiang** [comment]
Hey @timpak, instead of adding a new locator for Blogs, could you try the more global locator `Button#ANY` and see if that works?

Thanks!

**Comment by timpak** [comment]
@austinchiang yes ```Button#ANY``` works. I'll use that instead.

**Comment by timpak** [comment]
@austinchiang I've updated the commit to use ```Buton#ANY``` and removed the new locator. Please review.

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55898

**Pull request closed without merging**
