### PR TITLE
LPS-103390 Remove unused code

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang 
This should fix 12 of the failing poshi tests. Let me know if this doesn't fix all of them.
Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
Hey @adolfopa:
1. The success message appears as expected when adding a doc through the admin view
2. The success message still does not appear when adding a doc through the site page, but it will appear once you navigate to the admin view for DM

I've uploaded a video [here](https://issues.liferay.com/browse/LPS-103390?focusedCommentId=2027965&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2027965) for reference. Could you please take a look? Thanks!

**Comment by adolfopa** [comment]
See https://github.com/austinchiang/liferay-portal/pull/628

**Pull request closed without merging**
