### PR TITLE
LPS-139938, LPS-139939, LPS-146953 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-139938
https://issues.liferay.com/browse/LPS-139939
https://issues.liferay.com/browse/LPS-146953

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@Hanlf can you please fix the rebase errors and resend? Thx

**Comment by Hanlf** [comment]
resent it here: https://github.com/liferay-lima/liferay-portal/pull/2742

**Pull request closed without merging**
