### PR TITLE
LPS-104530 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang !

I sent this PR to myself (see https://github.com/adolfopa/liferay-portal/pull/1155), and there were some D&M failures. Problem is that the CI is not giving me any more info other than the test is failing. Locally, things look ok, but before sending this to Brian I wanted to double check with you.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
@adolfopa Found the test results :)
`ci:test:relevant` - https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=870830949
`ci:test:stable` - https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=870833100

Tests look good. The Sharepoint failures are unrelated. I'll push to BChan. Thanks!

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/80910

**Pull request closed without merging**
