### PR TITLE
7.0.x-qa-28957

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-28957

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@patriciajeanperez @austinchiang maybe try upping the pause time to 5 seconds?  just to know whether pausing before save/publish helps the test or not.

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
https://github.com/austinchiang/liferay-portal/pull/56

**Pull request closed without merging**
