### PR TITLE
Master | LPS-96818

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-96818

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:contentpagereview

**Comment by Hanlf** [comment]
The above failures are not related to my pull, thanks!

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/79809

**Pull request closed without merging**
