### PR TITLE
master-lps-125009

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-125009

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1406<br></br>

**Comment by austinchiang** [comment]
@Jeremy-Ch we should make it clearer which ones are remote staging vs. local in the test name if we're adding more tests in the future

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1408<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/8f15745bc6f7~1...8f15745bc6f7)

**Pull request closed without merging**
