### PR TITLE
Master | LPS-104513

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-104513
https://issues.liferay.com/browse/LRQA-53950

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
'Just <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81338

**Pull request closed without merging**
