### PR TITLE
LPS-109842 / LPS-109845 Demodularize Image Editor

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang !

Here I'm changing how the Image Editor is wired up, collapsing multiple modules into one, and removing DS components.

This PR contains no functional nor visual changes, but as the way things are registered in OSGi is different, little things may have changed in the Image Editor (like the order in which different options show up).

If there are any failures, close the PR and I'll look into them

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/85970<br></br>

**Pull request closed without merging**
