### PR TITLE
Master | LPS-83416

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-83416

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:onlineediting

**Comment by Hanlf** [comment]
The failure are not related to my pull.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77627

See changes in https://github.com/brianchandotcom/liferay-portal/pull/77627/commits/6521ef6e12fe9a4d6af7674d60c6896492594b5b

**Pull request closed without merging**
