### PR TITLE
LRCI-xx Skip proxy setup for tomcat modules integration tests

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by 4lejandrito** [comment]
Hi @austinchiang, @yichenroy,

These are good results. The problem is that your credentials are wrong. I have tried locally with your credentials and I also got the `401 Unauthorized` error. I set my own credentials in my portal-ext.properties and the tests worked.

@austinchiang please let me know if you need any help generating a new set of credentials.

Thanks guys!

**Comment by austinchiang** [comment]
See https://github.com/yichenroy/liferay-portal/pull/170

**Pull request closed without merging**
