### PR TITLE
LRQA-42529 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-42529

7.1.x: https://github.com/austinchiang/liferay-portal-ee/pull/171

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:close @GinsonRen @Hanlf see my comment in https://github.com/GinsonRen/liferay-portal/pull/323#issuecomment-448143457

Also, Austin is on EVP this week. Please send pulls to @patriciajeanperez or directly to BChan.

**Comment by GinsonRen** [comment]
@jpince Since this is not urgent, I am going to keep this to Austin.

Re-send here:
https://github.com/austinchiang/liferay-portal/pull/335

**Pull request closed without merging**
