### PR TITLE
LPS-141135 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-141135

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/3330<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/6126fe72a57e~1...6126fe72a57e)

**Comment by austinchiang** [comment]
@Jeremy-Ch please make sure to think about what the main assertion of the test is when changing the name, not just add "can" or "cannot" in front of whatever the existing name is.

**Pull request closed without merging**
