### PR TITLE
LRQA-34843 | master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-34843

### CODE REVIEW

**Comment by pcwhite** [comment]
@anthony-chu

**Comment by austinchiang** [comment]
@pcwhite Please update your commit message to reflect your logical change.

**Comment by pcwhite** [comment]
@austinchiang @anthony-chu updated!

**Comment by austinchiang** [comment]
No test changes needed :)

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51792

**Pull request closed without merging**
