### PR TITLE
master-lps-96816

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-96816

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:contentpagereview

**Comment by liuxingye** [comment]
Both the **DisableContentPageCommentsAtSystemScope** and **ViewCommentListNavigation** are not related to my commits.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77484

**Pull request closed without merging**
