### PR TITLE
master-lps-124575

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-124575

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1193<br></br>

**Pull request closed without merging**
