### PR TITLE
LPS-102639 Same for google cloud natural language

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @austinchiang,

Can you please verify this fixes the original issue?

Thanks!

**Comment by 4lejandrito** [comment]
Hi @austinchiang,

Forget about this so far. I forgot that Yvonne already tested it: https://issues.liferay.com/browse/BPR-31604?focusedCommentId=1971237&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1971237.

I'll look into it.

**Comment by austinchiang** [comment]
ok, let me know if there is anything you'd like me to do after you investigate.

**Comment by austinchiang** [comment]
ci:test:autotagging

**Pull request closed without merging**
