### PR TITLE
LPS-110020 Wiki - remove alloyeditor from title field

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hi @austinchiang, 

in this pull, the "title" field in a Wiki page has been replaced from an AlloyEditor to a simple input. Also has been renamed from "titleEditor" to just "title". Please check if there are tests that may need to be updated. 

Thanks!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:wiki

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by ambrinchaudhary** [comment]
@austinchiang just pushed a commit that I forgot before, sorry! (but it should not affect the tests)

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/austinchiang/liferay-portal/pull/751

**Comment by austinchiang** [comment]
Everything will be consolidated in https://github.com/austinchiang/liferay-portal/pull/768

**Pull request closed without merging**
