### PR TITLE
LRQA-49570 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Running MB tests

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by austinchiang** [comment]
ci:test:messageboards

**Comment by austinchiang** [comment]
Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/74265

**Comment by patriciajeanperez** [comment]
Thanks, @austinchiang!

**Pull request closed without merging**
