### PR TITLE
LPS-111251 Accomodate HTML test

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
See https://github.com/ambrinchaudhary/liferay-portal/pull/338

**Pull request closed without merging**
