### PR TITLE
master-lps-133798

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-133798

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/2018<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/00644c813f9d~1...00644c813f9d)

**Pull request closed without merging**
