### PR TITLE
LPS-110014 Update the friendly url when the title changes

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[LPS-110014](https://issues.liferay.com/browse/LPS-110014) - Replace AlloyEditor in Title field in Knowledge Base Templates
[LPS-110598](https://issues.liferay.com/browse/LPS-110598) - Fields identification in Knowledge Base)

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:knowledgebase

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:knowledgebase

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:knowledgebase

**Comment by ambrinchaudhary** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
Hey @ambrinchaudhary looks like the friendly URL issue is still present. See screenshot in [this test](https://testray.liferay.com/reports/production/logs/test-1-13/1584986185739/test-portal-acceptance-pullrequest(master)/3759/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.CPKnowledgebase_AddKBArticlesViaKBAdmin/index.html.gz)

It also looks like there are some issues viewing the content field of a KB template after adding one. See screenshot [here](https://testray.liferay.com/reports/production/logs/test-1-13/1584986185739/test-portal-acceptance-pullrequest(master)/3759/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.CPKnowledgebase_AddTemplateCP/index.html.gz)

**Comment by austinchiang** [comment]
Since we need all tests to be stable today we're going to disable 90% of our KB tests for now. That's being done [here](https://github.com/brianchandotcom/liferay-portal/pull/86735). We'll have to reactivate the tests to properly test for this fix.

**Comment by ambrinchaudhary** [comment]
See https://github.com/austinchiang/liferay-portal/pull/723

**Pull request closed without merging**
