### PR TITLE
LPS-122985, LPS-122854 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-122985
https://issues.liferay.com/browse/LPS-122854

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Thanks for following up on this!

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1785<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/7cf54756a84d~1...7cf54756a84d)

**Pull request closed without merging**
