### PR TITLE
LPS-44217 Use TreeMapBuilder

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang !

Here I've fixed some of the issues with https://github.com/austinchiang/liferay-portal/pull/549. In case of failures, can you check if they're specific to this PR?

Thanks a lot!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@adolfopa Compile error during ant all:

`     [exec] BUILD SUCCESSFUL in 19s
     [exec] 3 actionable tasks: 3 executed
     [exec]

jar-sources:
      [jar] Building jar: D:\public\master-portal\portal-kernel\portal-kernel-sources.jar

install-portal-snapshot:
     [copy] Copying 1 file to D:\public\master-portal\portal-kernel
   [delete] Deleting directory D:\public\master-portal\.m2\com\liferay\portal\com.liferay.portal.kernel
[artifact:install] [INFO] Installing D:\public\master-portal\portal-kernel\portal-kernel.jar to D:\public\master-portal\.m2\com\liferay\portal\com.liferay.portal.kernel\5.0.0-SNAPSHOT\com.liferay.portal.kernel-5.0.0-SNAPSHOT.jar
[artifact:install] [INFO] Installing D:\public\master-portal\portal-kernel\portal-kernel-sources.jar to D:\public\master-portal\.m2\com\liferay\portal\com.liferay.portal.kernel\5.0.0-SNAPSHOT\com.liferay.portal.kernel-5.0.0-SNAPSHOT-sources.jar
   [delete] Deleting: D:\public\master-portal\portal-kernel\pom.xml
[propertyfile] Updating property file: D:\public\master-portal\.gradle\gradle.properties
     [echo] Executing Gradle task: deploy
   [delete] Deleting: D:\public\master-portal\null1378001278.properties
   [delete] Deleting: D:\public\master-portal\null1574007677.properties
   [delete] Deleting: D:\public\master-portal\null272417744.properties
   [delete] Deleting: D:\public\master-portal\null979946798.properties
   [delete] Deleting: D:\public\master-portal\null1503138950.properties

download-latest-artifact:

init-compile:

download-latest-artifact:

compile:

download-latest-artifact:

download-latest-artifact:

init-compile:

compile:

init-compile:

compile:

download-latest-artifact:

init-compile:

compile:

init-compile:
     [copy] Copying 1 file to D:\public\master-portal\util-slf4j\classes
     [copy] Copying 6 files to D:\public\master-portal\support-tomcat\classes
     [copy] Copying 5 files to D:\public\master-portal\util-bridges\classes
     [copy] Copied 8 empty directories to 7 empty directories under D:\public\master-portal\util-slf4j\classes

compile:
    [javac] Compiling 5 source files to D:\public\master-portal\util-slf4j\classes
     [copy] Copying 49 files to D:\public\master-portal\portal-test\classes
     [copy] Copied 17 empty directories to 4 empty directories under D:\public\master-portal\support-tomcat\classes
    [javac] Compiling 8 source files to D:\public\master-portal\support-tomcat\classes
    [javac] Compiling 4 source files to D:\public\master-portal\util-bridges\classes
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
     [copy] Copied 84 empty directories to 16 empty directories under D:\public\master-portal\portal-test\classes
    [javac] Compiling 87 source files to D:\public\master-portal\portal-test\classes
   [delete] Deleting: D:\public\master-portal\null1720148278.properties

download-latest-artifact:

init-compile:

build-common-java.compile:
     [copy] Copying 29 files to D:\public\master-portal\util-taglib\classes
    [javac] Compiling 237 source files to D:\public\master-portal\util-taglib\classes
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

compile:
   [delete] Deleting: D:\public\master-portal\null773586262.properties

download-latest-artifact:

build-common-java.init-compile:

init-compile:
     [copy] Copying 185 files to D:\public\master-portal\portal-impl\classes\com\liferay\portal\definitions
     [copy] Copying 8 files to D:\public\master-portal\portal-impl\classes\com\liferay\portal\deploy\dependencies
     [copy] Copying 12 files to D:\public\master-portal\portal-impl\classes\com\liferay\portal\tools\sql\dependencies
     [copy] Copying 1 file to D:\public\master-portal\portal-impl\classes
     [copy] Copying 1 file to D:\public\master-portal\portal-impl\classes
     [copy] Copying 392 files to D:\public\master-portal\portal-impl\classes
     [copy] Copied 456 empty directories to 340 empty directories under D:\public\master-portal\portal-impl\classes

build-common-java.compile:
     [copy] Copying 1 file to D:\public\master-portal\portal-impl\classes
    [javac] Compiling 2596 source files to D:\public\master-portal\portal-impl\classes
    [javac] D:\public\master-portal\portal-impl\src\com\liferay\portal\service\impl\LayoutSetLocalServiceImpl.java:201: error: cannot find symbol
    [javac]             catch (NoSuchVirtualHostException nsvhe) {
    [javac]                    ^
    [javac]   symbol:   class NoSuchVirtualHostException
    [javac]   location: class LayoutSetLocalServiceImpl
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
D:\public\master-portal\build.xml:118: The following error occurred while executing this line:
D:\public\master-portal\build.xml:285: The following error occurred while executing this line:
D:\public\master-portal\build-common-java.xml:52: Compile failed; see the compiler error output for details.

Total time: 12 minutes 14 seconds`

**Comment by adolfopa** [comment]
See https://github.com/austinchiang/liferay-portal/pull/586

**Pull request closed without merging**
