### PR TITLE
master-qa-49422

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-49422

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/75650

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1463<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/5ceeedaf6beb~1...5ceeedaf6beb)

**Pull request closed without merging**
