### PR TITLE
LPS-111411 Add wiki test suite

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:wiki

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Hey @ambrinchaudhary, a few issues:

- I'm still getting that typeerror in the CKEditor source field, and the html code is still not rendering properly
typeerror
- I think a title field got removed from Wiki Front Page (normal Wiki Pages are fine), so when I try to edit the Front Page it fails to publish because it cannot find the title field
Capture

Could you please take a look? Sorry for the back and forth!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
See https://github.com/ambrinchaudhary/liferay-portal/pull/340

**Comment by ambrinchaudhary** [comment]
See https://github.com/austinchiang/liferay-portal/pull/771

**Comment by ambrinchaudhary** [comment]
Hi Austin, I sent the fixes here: https://github.com/austinchiang/liferay-portal/pull/771: 
> Hey @ambrinchaudhary, a few issues:
> 
>     * I'm still getting that typeerror in the CKEditor source field, and the html code is still not rendering properly
>       typeerror

I'm not able to reproduce this error and this case works fine for me in local. But while checking the poshi error message, I was wondering if the test is ok. By default, the type of the wiki is Creole and this test (_**PGWiki#AddFrontPageWithHTMLFormat**_) is trying to check the html format. So maybe in _WikiPage.macro_ method _addFrontPagePG_, if `"${htmlSource}" == "true"` (which is the case) we should expand the configuration panel and then select "html". By doing this, the test result should work and render an "Home" link (`AssertTextEquals( locator1 = "WikiEntry#BODY_LINK", value1 = "${wikiPageContent}");`). If I am wrong , I'm totally lost with this failure :-(

>     * I think a title field got removed from Wiki Front Page (normal Wiki Pages are fine), so when I try to edit the Front Page it fails to publish because it cannot find the title field
>       Capture

I fixed this bug in the last commit. 

> 
> Could you please take a look? Sorry for the back and forth!

**Pull request closed without merging**
