### PR TITLE
LPS-155142 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-155142

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by Jeremy-Ch** [comment]
Hey @austinchiang  Could you help to add the property (property portal.release = "false";) to the test? If need I to update it, please let me know, thanks.

**Comment by austinchiang** [comment]
Pushed to Lima.
https://github.com/liferay-lima/liferay-portal/pull/3326

**Pull request closed without merging**
