### PR TITLE
master-lps-104327

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-104327

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by liuxingye** [comment]
@austinchiang you can close this, I've resend this with my changes here https://github.com/austinchiang/liferay-portal/pull/656

**Pull request closed without merging**
