### PR TITLE
LPS-160773 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-160773

**Original Tests Distribution:**

<b style="font-weight:normal;" id="docs-internal-guid-0a370ed8-7fff-8a25-6605-2ca73dfff127"> 

Test File Name | Test counts
-- | --
KBAdmin | 33
KBDisplayWidget | 32
KBUsercase | 12
KBUpgeade | 3
KBWorkflow | 2
KBArticleWidget | 1
KBLocalization | 1
KBPermissions | 1
KBNotification | 1
Total | 86

</b>

**New Tests Distribution:**

<b style="font-weight:normal;" id="docs-internal-guid-0a370ed8-7fff-8a25-6605-2ca73dfff127"> 

Test File Name | Test counts
-- | --
KBAdmin | 6
KBArticle | 19
KBDisplayWidget | 26
KBUpgrade | 3
KBWorkflow | 3
KBArticleWidget | 1
KBLocalization | 1
KBPermissions | 1
KBNotification | 1
KBFolder | 5
KBTemplates | 3
KBExportImport | 3
KBSearch | 4
KBHierarchy | 9
Total | 85

</b>

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
