### PR TITLE
LPS-103390 Remove unused code

### PR DESCRIPTION
**Pull request by adolfopa**
The previous pull fixed only the "edit" case, not the "create" one 🤦‍♂ 

Let me know if this doesn't fix everything.

Thanks!

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
@adolfopa From the automation results it looks like the success message is still missing when adding a document using the multiple file uploader in the site page (single file uploading is fine now). I'll double check locally.

**Comment by austinchiang** [comment]
Confirmed locally. The success message does not appear after using the **multiple file uploader** in the **site page.** The message appears once you navigate to site admin.

**Comment by adolfopa** [comment]
See https://github.com/austinchiang/liferay-portal/pull/632

**Pull request closed without merging**
