### PR TITLE
master-lps-134267

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-133615
https://issues.liferay.com/browse/LPS-134004
https://issues.liferay.com/browse/LPS-134267

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/1073<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/d3b3d8b5176e~1...d3b3d8b5176e)

**Pull request closed without merging**
