### PR TITLE
Revert "LPS-193718 Only enable for master, Alan will revert when all violations are fixed on other branches"

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:wiki

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
I think they are referring to different jobs run on the pull.

SF job passed :heavy_check_mark: 
ci:test:wiki ran but had some tests that failed :x:

**Comment by austinchiang** [comment]
ci:test:relevant failures are not related

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
ci:forward:force

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/140435

**Pull request closed without merging**
