### PR TITLE
master-qa-48541

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-48541

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Songyuewen** [comment]
cc/ @brianwulbern, @GinsonRen

**Comment by Songyuewen** [comment]
ci:test

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72287

**Pull request closed without merging**
