### PR TITLE
master-lps-126084

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-126084

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1406

**Pull request closed without merging**
