### PR TITLE
master-lps-97983

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-97983

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
The SF failure is not related to my commits.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78268

**Pull request closed without merging**
