### PR TITLE
Master | LPS-122844 and LPS-122952

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-122844
https://issues.liferay.com/browse/LPS-122952

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Good work @Hanlf

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/999<br></br>

**Pull request closed without merging**
