### PR TITLE
LRQA-46291, LRQA-46314 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-46291
https://issues.liferay.com/browse/LRQA-46314

Master only

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
@austinchiang, just because I haven't sent you pulls in a while. jk, pushing to you because this adds a test to acceptance. thanks!

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan. Thanks @nikki-pru @patriciajeanperez !
https://github.com/brianchandotcom/liferay-portal/pull/67118

**Pull request closed without merging**
