### PR TITLE
LPS-111251 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-111251

### CODE REVIEW

**Comment by john-co** [comment]
Hi @austinchiang, I was working on the test fixes for LPS-111251 until I saw [ambrin's comment](https://github.com/ambrinchaudhary/liferay-portal/pull/326#issuecomment-607496696). Please feel free to piggy back from these if helpful.

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by ambrinchaudhary** [comment]
@austinchiang please don't send it yet to Brian, I'm afraid the solution if not the best because editor in Wiki must configurable at system settings

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by ambrinchaudhary** [comment]
See https://github.com/austinchiang/liferay-portal/pull/743

**Pull request closed without merging**
