### PR TITLE
LPS-109697 change pagination to make it a multiple of 4

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/710<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/640ea1ef3c58~1...640ea1ef3c58)

**Comment by austinchiang** [comment]
Oops, testing in https://github.com/austinchiang/liferay-portal/pull/710. @AliciaGarciaGarcia Will send to BChan if it looks good

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/86365<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/9e9521f227db~1...9e9521f227db)

**Pull request closed without merging**
