### PR TITLE
Master lps 151515

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-149692
https://issues.liferay.com/browse/LPS-151515

CC/ @adolfopa Update the backend test here: https://github.com/austinchiang/liferay-portal/pull/1304/commits/899c3fcba385924008477081324bb8ecaaf49735

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The failure is not related to this failure(caused by https://issues.liferay.com/browse/LPS-151646), re-run it.

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
