### PR TITLE
Master | LPS-110593

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-110593

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/163<br></br>

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/89752<br></br>

**Pull request closed without merging**
