### PR TITLE
LPS-154389, LPS-154396 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-154396
https://issues.liferay.com/browse/LPS-154389

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Good work @chaowang-123

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Fixed commit messages and resent in https://github.com/liferay-lima/liferay-portal/pull/3096

**Pull request closed without merging**
