### PR TITLE
master-lrqa-51710

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-51710

@austinchiang I send this to you first since it's refactored.

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:contentpagereview

**Comment by liuxingye** [comment]
ci:test:contentpagereview

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
LocalFile.ContentPageReview#ViewCommentListNavigation is not related my commits, we can track it more.

**Comment by austinchiang** [comment]
Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/77627

See changes in the pull.

**Pull request closed without merging**
