### PR TITLE
LPS-130240 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-131978
https://issues.liferay.com/browse/LPS-132569

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Nice work @Hanlf !

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
