### PR TITLE
LRQA-39752 | Master

### PR DESCRIPTION
**Pull request by acbbennett**
https://issues.liferay.com/browse/LRQA-39752

### CODE REVIEW

**Comment by acbbennett** [comment]
@austinchiang per our conversation, I decided to use the two functions in the macro for for da20369 because the same method is used elsewhere and no other navigation macros existed for the purpose. If it comes up again, it may be worth creating a new macro.

**Comment by acbbennett** [comment]
Confirmed fix is unnecessary on 7.0.x
(one related test failed for unrelated reason)

**Comment by austinchiang** [comment]
SF for @acbbennett: 
- Please modify https://github.com/austinchiang/liferay-portal/pull/281/commits/d1af2fc7b8c45f04414876ab0fc731ff7f81e301 so that the locator is able to be used properly when there are multiple threads on the page

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56932

**Pull request closed without merging**
