### PR TITLE
master |  LRQA-44976, LRQA-45679, LRQA-45259, LRQA-45065

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-44976
https://issues.liferay.com/browse/LRQA-45679
https://issues.liferay.com/browse/LRQA-45259
https://issues.liferay.com/browse/LRQA-45065

Please cherry pick to 7.1.x, thanks! 

cc/ @ginsonren, @brianwulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66609

**Pull request closed without merging**
