### PR TITLE
master-lrqa-52599

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-52599

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@liuxingye  Don't use pauses when possible. If this test fails in CI because it is moving too fast, it is better to wait for an element to be present instead of using the Pause function.

Pushed to BChan https://github.com/brianchandotcom/liferay-portal/pull/79429

**Comment by liuxingye** [comment]
@austinchiang Got it, thanks.

**Pull request closed without merging**
