### PR TITLE
Lps 193718 20230902

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:wiki

**Comment by austinchiang** [comment]
ci:test:wiki

**Comment by austinchiang** [comment]
ci:test:wiki

**Comment by ling-alan-huang** [comment]
ci:test:wiki

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Hey @ling-alan-huang looks like there's a rebase issue at head now. Could you please take a look?

**Comment by ling-alan-huang** [comment]
Got it.

**Comment by ling-alan-huang** [comment]
Closing, I resent here https://github.com/austinchiang/liferay-portal/pull/1500
and will add more commits later.

**Comment by ling-alan-huang** [comment]
ci:close

**Pull request closed without merging**
