### PR TITLE
LRQA-47415 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-47415

Master only

Please wait for ci:test:relevant to finish, thanks!

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70003

**Pull request closed without merging**
