### PR TITLE
LPS-126138, LPS-126143, LPS-126144 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-126138
https://issues.liferay.com/browse/LPS-126143
https://issues.liferay.com/browse/LPS-126144

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/2010<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/5270b0ff4bf4~1...5270b0ff4bf4)

**Pull request closed without merging**
