### PR TITLE
LPS-107367 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-107367

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
The SF issue is not related to this PR. It is a common issue.

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
