### PR TITLE
LPS-125337, LPS-122724 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-125337
https://issues.liferay.com/browse/LPS-122724

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1336

**Pull request closed without merging**
