### PR TITLE
master-lps-133065

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-133065

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@Jeremy-Ch No need to mention Google in the test name if it's already mentioned in the test/macro file

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/2143<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/e91b2810f890~1...e91b2810f890)

**Pull request closed without merging**
