### PR TITLE
master | LRQA-44585, LRQA-45799, LRQA-45861

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-44585
https://issues.liferay.com/browse/LRQA-45799
https://issues.liferay.com/browse/LRQA-45861

these issues also affect 71 branch, please cherry-pick it, thanks!

cc/ @ginsonren, @BrianWulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66510

**Pull request closed without merging**
