### PR TITLE
LPS-110016,LPS-110017 Added obsolete properties

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey Austin, this is the pull that Brian didn't merge: 

> 1.) Can you modify VerifyProperties#OBSOLETE_PORTAL*
> so that if anyone has a portal-ext.properrties set with the now removed properties, they will ber warned on startup.
> 2.) ci.test.suite.description[redirect]=Run Redirection tests.
> Looks very different from all the other test descriptions. Please conform unless there is a reason not to.

I solved the point 1). Could you please check the point 2) please? 
Thanks!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/769<br></br>

**Comment by austinchiang** [comment]
#2 will be dealt with here https://github.com/austinchiang/liferay-portal/pull/768

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@ambrinchaudhary  SF issue, could you take a look?

**Pull request closed without merging**
