### PR TITLE
LPS-158058, LPS-158980, LPS-158048, LPS-158051, LPS-158053 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-158058
https://issues.liferay.com/browse/LPS-158980
https://issues.liferay.com/browse/LPS-158048
https://issues.liferay.com/browse/LPS-158051
https://issues.liferay.com/browse/LPS-158053

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/3308<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/55e78ee46f47~1...55e78ee46f47)

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/john-co/liferay-portal/pull/477<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/55e78ee46f47~1...55e78ee46f47)

**Pull request closed without merging**
