### PR TITLE
LRQA-36694 | master

### PR DESCRIPTION
**Pull request by andrewlam78**
https://issues.liferay.com/browse/LRQA-36694

### CODE REVIEW

**Comment by andrewlam78** [comment]
ci:test

**Comment by austinchiang** [comment]
Looks good, thanks @andrewlam78 !

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/53707

**Comment by austinchiang** [comment]
Haha woops, actually could you put the LRQA # in your commit message?

`LRQA-36694 Update locator..` Thanks!

**Comment by austinchiang** [comment]
No test changes needed :)

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/53719

**Pull request closed without merging**
