### PR TITLE
LPS-110020, LPS-110019, LPS-111251, LPS-111411, LRQA-57648 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-110020
https://issues.liferay.com/browse/LPS-110019
https://issues.liferay.com/browse/LPS-111251
https://issues.liferay.com/browse/LPS-111411
https://issues.liferay.com/browse/LRQA-57648

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:wiki

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@ambrinchaudhary Semantic versioning error. Can you take a look?

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
See https://github.com/ambrinchaudhary/liferay-portal/pull/342

**Pull request closed without merging**
