### PR TITLE
LPS-149977, LPS-149976, LPS-150073 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-149977
https://issues.liferay.com/browse/LPS-149976
https://issues.liferay.com/browse/LPS-150073

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@Jeremy-Ch please make sure to update the tests in the test map

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2940

**Pull request closed without merging**
