### PR TITLE
LPS-149066 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-149066

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@Jeremy-Ch  Please see https://github.com/liferay-lima/liferay-portal/pull/2838.

We don't need the portal.acceptance=false. This was an old convention that has now changed using @ignore = "test stub"

**Comment by austinchiang** [comment]
@Jeremy-Ch found another issue and resent here https://github.com/liferay-lima/liferay-portal/pull/2839

**Pull request closed without merging**
