### PR TITLE
master-lps-136815

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-136815
https://issues.liferay.com/browse/LPS-136817
https://issues.liferay.com/browse/LPS-136818
https://issues.liferay.com/browse/LPS-136819
https://issues.liferay.com/browse/LPS-136820

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by liuxingye** [comment]
@austinchiang I removed `PendingEntryWillNotBePublishedToLive` since it is covered by `DMLocalStaging#PublishFolderWithWorkflow`. Thanks

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/2275<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/b99f011fe7d7~1...b99f011fe7d7)

**Pull request closed without merging**
