### PR TITLE
LPS-85900 change label to Name for the documents on edit and table view

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @austinchiang 

I send you this because we changed the label "Title" on Documents to "Name" and I don't know if there is some poshi test in which changes are needed.
thanks!

**Comment by AliciaGarciaGarcia** [comment]
cc/ @adolfopa

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/86127<br></br>

**Pull request closed without merging**
