### PR TITLE
master | LRQA-44618, LRQA-44965

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-44965
https://issues.liferay.com/browse/LRQA-44618

These two fixes are master only, please don't cherry-pick to 71, thanks!

cc/ @ginsonren, @brianwulbern

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
There were some rebase errors that I fixed. 

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66537

**Pull request closed without merging**
