### PR TITLE
Master | LPS-159175, LPS-163037

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-159175
https://issues.liferay.com/browse/LPS-163037

Will apply the edit JSON macro to other KB tests under [LPS-163259](https://issues.liferay.com/browse/LPS-163259)

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/3496<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/7fe08a3a70f5~1...7fe08a3a70f5)

**Comment by Hanlf** [comment]
@austinchiang Oh, I am sorry, forgot about it.

**Pull request closed without merging**
