### PR TITLE
LPS-149975, LPS-149972 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-149975
https://issues.liferay.com/browse/LPS-149972

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@Jeremy-Ch did these tests pass locally? I don't see any test reports

**Comment by Jeremy-Ch** [comment]
Hi @austinchiang These tests were passed locally. JIRA was unable to upload html file due to some JIRA issues before, but I still run every test locally before submitting it. For now, looks like the issue has been fixed.

**Comment by austinchiang** [comment]
@Jeremy-Ch Please make sure to communicate if there are issues that prevent you from uploading, or run it in CI and link the results. Thanks

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
