### PR TITLE
LPS-110014 Type in CKEditor

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
@ambrinchaudhary looks like the FriendlyURL does not dynamically update with inputs in the title field. Can we fix that? I'll send the test fixes in ahead of time. Thanks!

**Comment by ambrinchaudhary** [comment]
https://github.com/austinchiang/liferay-portal/pull/715

**Pull request closed without merging**
