### PR TITLE
master-qa-49412

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-49412

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan.
See changes here: https://github.com/brianchandotcom/liferay-portal/pull/76018/commits/1f05f5ba9ff56bb2ade9115786ab8c6cce245565

**Comment by liuxingye** [comment]
@austinchiang Noticed the changes, thanks!

**Pull request closed without merging**
