### PR TITLE
master-lps-121448

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-121448
https://issues.liferay.com/browse/LPS-120408

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
This error is not related to this request, I will SF later.

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/837<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/4beb978515c9~1...4beb978515c9)

**Pull request closed without merging**
