### PR TITLE
master-lps-129886

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-129936

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by Jeremy-Ch** [comment]
@austinchiang The three DMLocalization failures are caused by escape issues. They all related to download. The file name will be escaped from `これは文書です.txt` to `%E3%81%93%E3%82%8C%E3%81%AF%E6%96%87%E6%9B%B8%E3%81%A7%E3%81%99.txt` after downloading. We have two solutions as below:

1. Remove the assertion step` DMDocument.assertFileNameFromTempFolder(downloadedFileName = "これは文書です.txt");` not assert that  the file name from the server local, we just to test the download progress.
2. Update the assertion step `DMDocument.assertFileNameFromTempFolder(downloadedFileName = "これは文書です.txt");` to `DMDocument.assertFileNameFromTempFolder(downloadedFileName = "%E3%81%93%E3%82%8C%E3%81%AF%E6%96%87%E6%9B%B8%E3%81%A7%E3%81%99.txt");`. Obey the server's escaping rules.


Failed tests:
LocalFile.DMLocalization#CanDownloadJapaneseFile
LocalFile.DMLocalization#CanDownloadJapaneseFileByFileName
LocalFile.DMLocalization#CanDownloadJapaneseFileByTitle

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
