### PR TITLE
master-lps-104376

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-106000
https://issues.liferay.com/browse/LPS-106001
https://issues.liferay.com/browse/LPS-106002
https://issues.liferay.com/browse/LPS-106005
https://issues.liferay.com/browse/LPS-106006

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82246<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/a3273e2c5e10~1...a3273e2c5e10) <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82248<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/61dc0b71ee4f~2...61dc0b71ee4f) <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
