### PR TITLE
LPS-78357 Renaming searchURL to portletURL

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @austinchiang,

Can you please check if there are any functional tests breaking with this changes?

If you are happy with it please forward it.

Thanks!

/cc @carloslancha

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by austinchiang** [comment]
Hey @4lejandrito I renamed the last commit you pushed from `LPS-79417` to `LPS-78357` since it looks like the latter refers to Social Bookmarks whereas your changes were made in DM. Please let me know if this was done in error.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56891

Thanks!

**Comment by 4lejandrito** [comment]
Thanks @austinchiang. Nice catch!

**Pull request closed without merging**
