### PR TITLE
LPS-110014 Rename variable, as this is not an editor anymore

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @austinchiang,

we are removing alloyeditor in some places and replacing them with simple inputs. Would you mind checking if this produces poshi errors that can be fixed? 

It happened here as well: https://github.com/brianchandotcom/liferay-portal/pull/86465

Thank you!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@ambrinchaudhary looks like this was merged already in https://github.com/brianchandotcom/liferay-portal/pull/86479. It caused most of our knowledge base tests to fail. I'll close this ticket and file a test fix for it, thanks!

**Comment by austinchiang** [comment]
Woops I see a few more commits. I'll go ahead and fix the tests and send to BChan

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/713<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/a7eed8a0dbfa~1...a7eed8a0dbfa)

**Pull request closed without merging**
