### PR TITLE
LRQA-57539 Use different path to assert message

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang 

I've tried to reproduce the issue following the POSHI steps as closely as I could, but I'm unable to reproduce the failing test locally.

Can you try to reproduce this locally?

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Hey @adolfopa I think this is a CI issue, in particularly with some instability with our Sharepoint servers.
- I was unable to reproduce the failures locally
- The Sharepoint test that failed in this pull (`CPSharepoint#ViewOriginalFileExtensionAfterUnsuccessfulExtensionChange`) is different than the previously failing test (`CPSharepoint#MoveCheckedoutDocumentToFolder`) which happens to be passing now. So we are playing whack-a-mole :hammer:
- After searching on JIRA I found that this failure [was already happening on CI](https://issues.liferay.com/browse/LRCI-441) and has appeared recently on other branches. So it is not specific to this pull. I'm going to try to escalate this issue to the CI team. But in the meantime let me know what you would like to do with this pull. Thanks!

**Comment by adolfopa** [comment]
Thanks a lot @austinchiang ! I think we can wait for a little while to give time for the CI guys to find the problem. I'll resend the PR in a couple of days.

Thanks!

**Comment by austinchiang** [comment]
@adolfopa IT rebuilt the problematic Sharepoint server so I think things should be good now. Can you fix the branch conflicts and try running the Sharepoint suite again?

**Comment by adolfopa** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1400

**Pull request closed without merging**
