### PR TITLE
Master | LPS-114310, LPS-119908

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-114310
https://issues.liferay.com/browse/LPS-119908

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/789<br></br>

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/861<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/10b6eded6ca2~1...10b6eded6ca2)

**Pull request closed without merging**
