### PR TITLE
LPS-141550, LPS-141551... | Master 

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-141550
https://issues.liferay.com/browse/LPS-141551
https://issues.liferay.com/browse/LPS-141552
https://issues.liferay.com/browse/LPS-141555
https://issues.liferay.com/browse/LPS-141558
https://issues.liferay.com/browse/LPS-141565
https://issues.liferay.com/browse/LPS-142620

Hi @austinchiang , 
I want to add lima-upgrade suite on CI to test the lima upgrade tests more easily, could please review the commit: https://github.com/austinchiang/liferay-portal/commit/0c6607791d4c049d82b54f8ffceff0f8269feab3
For the rest commits, just updated tests to cover more test scenarios, no new tests under this PR.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
