### PR TITLE
LPS-130327, LPS-130334 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Update test to assert the fragment heading according to the browser types.

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/carlosbrichete/liferay-portal/pull/23

**Pull request closed without merging**
