### PR TITLE
LRQA-35642 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-35642

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
changes are master only, thanks! @austinchiang

**Comment by austinchiang** [comment]
Just started reviewing

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/52528

**Pull request closed without merging**
