### PR TITLE
LRQA-34393 | 7.0.x

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-34393

This is only for 7.0.  Thanks!

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
Oops, this should already be in source.

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/945<br></br>

**Comment by brianwulbern** [comment]
My bad, dropped a ball that stayed on the ground for 3.5 years, lol.

**Pull request closed without merging**
