### PR TITLE
master-qa-28957

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-28957

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
Retested here: https://github.com/austinchiang/liferay-portal/pull/58

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/david-gutierrez-mesa/liferay-portal/pull/89<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/e8fa95a28a06~1...e8fa95a28a06)

**Pull request closed without merging**
