### PR TITLE
master-qa-39586

### PR DESCRIPTION
**Pull request by felix3508**
https://issues.liferay.com/browse/LRQA-39586

### CODE REVIEW

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test:autotagging

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:test:bulkediting

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
ci:test:messageboards

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by austinchiang** [comment]
ci:test:sharing

**Comment by austinchiang** [comment]
ci:test:onedrive

**Comment by austinchiang** [comment]
ci:test:contentpagereview

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by austinchiang** [comment]
ci:test:seo

**Comment by austinchiang** [comment]
See https://issues.liferay.com/browse/LRQA-39586?focusedCommentId=2046597&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2046597

**Pull request closed without merging**
