### PR TITLE
LPS-99551 Configure single Item Selectors

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @austinchiang, 

this is the PR where we removed the footer in the Item Selector on those cases where we can select just an item. So as soon as the user clicks an item, the dialog is selected. I guess we have to change the poshi tests that checks that and have failed in CI. (In the last commit you can see the files/modules changed)

Thanks for your help!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:lima

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** <br><br>:hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81390

**Pull request closed without merging**
