### PR TITLE
LPS-104571 SF

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang!

Up until now, when editing an element (Blog or Docuemnt) from the Shared Assets widget, the edit view would open in a popup. I've changed everything so that it is opened in a regular control panel page. I hope this doesn't break too many tests.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:sharing

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
Hey @adolfopa just a heads up, our tests are currently failing due to https://issues.liferay.com/browse/LPS-104889. I'll test with a workaround for now

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/624<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/ed4f044ddabc~2...ed4f044ddabc) <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/81548<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/e3fec5c9a927~1...e3fec5c9a927) <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/81549<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/75759dad1e0e~1...75759dad1e0e) <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
