### PR TITLE
LRQA-38873 | Master

### PR DESCRIPTION
**Pull request by acbbennett**
https://issues.liferay.com/browse/LRQA-38873

### CODE REVIEW

**Comment by austinchiang** [comment]
Hey @acbbennett please merge the last two commits into one. They are the same logical change.

**Comment by acbbennett** [comment]
@austinchiang commits merged

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56112

**Pull request closed without merging**
