### PR TITLE
LPS-157573 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-157573

Tried to shorten the wait time of https://github.com/austinchiang/liferay-portal/pull/1380/commits/9916033d028ec3a76890664769e8a70da93e221b#diff-f8e3b8c8b8edbce61847491911f0ea698cdc724cc3642684d9c70b84771cd6efR2536, but it caused a flaky failure, so keep waiting for 2 minutes.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Testing in https://github.com/austinchiang/liferay-portal/pull/1381

**Comment by austinchiang** [comment]
Sent to Lima. https://github.com/liferay-lima/liferay-portal/pull/3221

**Pull request closed without merging**
