### PR TITLE
master-qa-48672

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-48672

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
cc/ @brianwulbern, @GinsonRen

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72378

**Pull request closed without merging**
