### PR TITLE
LPS-149059, LPS-148984, LPS-149971 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-149971
https://issues.liferay.com/browse/LPS-148984
https://issues.liferay.com/browse/LPS-149059

Hi @austinchiang, 
For LPS-149971, it has automated an XSS issue but uses an HTML file with directory indexing. I think it's special enough to be covered by the POSHI test. 
Thanks.

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
