### PR TITLE
LPS-123269 | master

### PR DESCRIPTION
**Pull request by Hanlf**
@austinchiang ,
Have not validated the Vimeo and Twitch video URL. Will add them after [LPS-124227](https://issues.liferay.com/browse/LPS-124227) is merged.
I'm worried that it will affect Beck's tomorrow's work, so I will push it to you first, then he can start his automation work base on this pull.

cc/ @liuxingye

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1163<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/014079d928bb~3...014079d928bb)

**Comment by austinchiang** [comment]
@Hanlf make sure to run poshi validation, thanks!

**Comment by Hanlf** [comment]
got it, thanks!

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1164<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/1feecad45911~3...1feecad45911)

**Pull request closed without merging**
