### PR TITLE
LPS-166731 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-166731

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
See the test results [here](https://github.com/Jeremy-Ch/liferay-portal/pull/135).

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/3654<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/8f2c6918324b~1...8f2c6918324b)

**Comment by austinchiang** [comment]
@Jeremy-Ch since upgrades tests [are not supported](https://issues.liferay.com/browse/LPS-166159) I am excluding them from the query

**Pull request closed without merging**
