### PR TITLE
LRQA-31084 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-31084

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by austinchiang** [comment]
No test changes needed :)

**Comment by austinchiang** [comment]
Pushed to BChan.
https://issues.liferay.com/browse/LRQA-31084

**Pull request closed without merging**
