### PR TITLE
LPS-77236 Using clay:navigation-bar in admin

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

This is caused by the problem fixed here: https://github.com/brianchandotcom/liferay-portal/pull/54836.

That code is already on master so this should not happen again.

ci:reopen

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54967

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
