### PR TITLE
master-lps-104192

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-108319
https://issues.liferay.com/browse/LPS-108321
https://issues.liferay.com/browse/LPS-108322
https://issues.liferay.com/browse/LPS-108323

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/84488<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/5220e82486ad~3...5220e82486ad)

**Pull request closed without merging**
