### PR TITLE
LPS-129115, LPS-129135, LPS-129141, LPS-129977 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-129977
https://issues.liferay.com/browse/LPS-129141
https://issues.liferay.com/browse/LPS-129115
https://issues.liferay.com/browse/LPS-129135

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1722<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/c9f36e976ba2~1...c9f36e976ba2)

**Comment by austinchiang** [comment]
@liuxingye Also see https://issues.liferay.com/browse/LPS-130176. Found the assertion error in your poshi report

**Pull request closed without merging**
