### PR TITLE
LRQA-65881, LPS-128714, LPS-128717 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-65881
https://issues.liferay.com/browse/LPS-128714
https://issues.liferay.com/browse/LPS-128717

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Repush it to add a new test: https://issues.liferay.com/browse/LPS-128473

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
