### PR TITLE
master-qa-127165

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LPS-127165

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1522<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/ed9eb74d1337~1...ed9eb74d1337)

**Pull request closed without merging**
