### PR TITLE
LPS-111232 Replace <liferay-ui:input-editor> with <liferay-editor:editor> in blogs-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @austinchiang
in this PR we removed AlloyEditor in the title and subtitle fields in Blogs. I am sending this to you first so you can check if there are tests failing or not.

There will be more pulls like these (changes made in Announcements, Wiki & Comments)

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/740<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/bb7e9398e1e8~1...bb7e9398e1e8)

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/752<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/f9ef33135545~1...f9ef33135545)

**Pull request closed without merging**
