### PR TITLE
LPS-91711

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang

This PR changes some little details in the KB UI.  I'm sending it to you in case
it breaks any functional tests.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by austinchiang** [comment]
Pushed to BChan. Thanks!
https://github.com/brianchandotcom/liferay-portal/pull/74327

**Pull request closed without merging**
