### PR TITLE
master-lps-104311

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-104311

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82669<br></br> <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
@Jeremy-Ch  Make sure to capitalize the first word in your commit messages

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82670<br></br> <br><br>Sent from GitHub :octocat:

**Comment by Jeremy-Ch** [comment]
> @Jeremy-Ch Make sure to capitalize the first word in your commit messages

@austinchiang It's my mistake, so sorry about that and thank you for your mention.

**Comment by austinchiang** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/82707

**Pull request closed without merging**
