### PR TITLE
LPS-110019, LPS-110020, LPS-111251, LPS-111411 Wiki CKEditor tests

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
About failing tests: 

1. **PGWiki#AddFrontPageWithHTMLFormat**
I'm not able to reproduce this error and this case works fine for me in local. But while checking the poshi error message, I was wondering if the test is ok. By default, the type of the wiki is Creole and this test (PGWiki#AddFrontPageWithHTMLFormat) is trying to check the html format. So maybe in WikiPage.macro method addFrontPagePG, if "${htmlSource}" == "true" (which is the case) we should expand the configuration panel and then select "html". By doing this, the test result should work and render a "Home" link (AssertTextEquals( locator1 = "WikiEntry#BODY_LINK", value1 = "${wikiPageContent}");). If I am wrong , I'm totally lost with this failure :-(

2. **PGWiki#AddPageWithChildPage**, **PGWiki#AddPageWithHTMLFormat** and **PGWiki#DeletePage**  tests have references to AlloyEditor

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/772<br></br>

**Comment by austinchiang** [comment]
Thanks for the catch @ambrinchaudhary ! I think you are spot on

**Pull request closed without merging**
