### PR TITLE
LPS-107284 It should say "sites" until Depots are released

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang 

I've kept the old "Workspaces" lang key so we don't lose the existing translations. Can you tell Brian when you send the pr so he doesn't remove it?

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
'Just

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/83453<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/3e0f5f151c54~1...3e0f5f151c54)

**Pull request closed without merging**
