### PR TITLE
master-qa-40026

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-40026

7.1.x: [austinchiang/liferay-portal-ee#179](https://github.com/austinchiang/liferay-portal-ee/pull/179)

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
SF for @Sharryxue :
- `rate` used in this context is not a noun so I changed it to `rating`

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73765

**Pull request closed without merging**
