### PR TITLE
LPS-96265 Delete unused code.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @austinchiang !

We would need to check out the old Sharepoint Connector after the migration to axis 2. 

Could you take a look at this pull.

I know we would need to wait until the current plugin is released on Marketplace before we can merge it.

Thanks!!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sharepoint

**Comment by Hanlf** [comment]
Hi @cgoncas ,
The setting fields are not suitable for SharePoint, no Library Name, Library Path (Optional), Server Version (2010 or 2013) and Site URL to set SP repository.
SPsettings

Another issue: If select CMIS Repository (AtomPub) for the Repository Type, and select Sharepoint again, then no setting fields show up.
noSettingField

**Comment by cgoncas** [comment]
Hey @Hanlf !!

Maybe this issue is related to the way the bunde has been package? Have you tried an ant all?

I've sent you a video recording of the Sharepoint selection and all the fields are shown :(.

Thanks!

**Comment by cgoncas** [comment]
After talk with @Hanlf I have been able to reproduce the bug.

**Comment by cgoncas** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
Tests look much better now: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=960260174

**Comment by Hanlf** [comment]
Hi @cgoncas 

Both issues I found above are gone and no functional tests failed at this pull now.
But there are two backend failures: 
modules-semantic-versioning-jdk8 failure: 
`Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.sharepoint.connector-4.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.sharepoint.connector/4.0.0/e7b57ef9fa4ad270fd7571195cdf08ab3363bb8c/com.liferay.sharepoint.connector-4.0.0.jar`
and
central-requirements-jdk8 failure:
`Incorrect repository URL in modules/dxp/apps/sharepoint/sharepoint-connector/build.gradle, please use https://repository-cdn.liferay.com/nexus/content/groups/public instead`

/cc @austinchiang No TF needed.

**Comment by cgoncas** [comment]
Thanks a lot @Hanlf

I will fix it on moday :)

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/677<br></br>

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
@cgoncas pull looks good. Will wait until FP4 is released before sending this to BChan. Thanks!

**Pull request closed without merging**
