### PR TITLE
master-lps-115524

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-115524

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/258<br></br>

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/258/commits/8390cc706e6c132e3b6edcd543533d8662e8b6b7

**Pull request closed without merging**
