### PR TITLE
LPS-97376 Condition no longer needed

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Hello @austinchiang 

Can you do me the favor of check if the behavior with the changes is the desired and check that the bug is properly solved and that we don't break anything else??

thanks!

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:messageboards

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
Hey @AliciaGarciaGarcia , the results look pretty good [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=701898837) (the two failures are unrelated to the pull). I also manually validated that the fix solves the bug. 

One thought I had was having "stale" message boards notifications have the same behavior as what we have in Sharing notifications. If a notification is not relevant anymore, then the link to the post is removed and is replaced by the text `Notification no longer applies. Notification for Sharing was deleted.` What do you think?

I am fine either way.

**Comment by 4lejandrito** [comment]
Hi @austinchiang,

We've heard opinions on both sides of having stale notificactions. I suggest you create a feature request so that Pablo can review it. Is that ok?

Rgarding the bug, can you please forward to Brian?

Thanks!

**Comment by austinchiang** [comment]
Sure thing!

**Comment by austinchiang** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Thanks!

**Pull request closed without merging**
