### PR TITLE
LPS-148264 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-148264

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Please see changes @jaydawu Can you please backport this after it is merged in master? Thx in advance

**Comment by austinchiang** [comment]
ci:forward

**Comment by jaydawu** [comment]
@austinchiang Ok, no problem.

**Pull request closed without merging**
