### PR TITLE
LPS-103696 Input is created on save, first time will not be available

### PR DESCRIPTION
**Pull request by adolfopa**
@austinchiang I'm sending this to you to double check that the two test failures caused by this are really fixed.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81546

**Pull request closed without merging**
