### PR TITLE
master-lps-102417

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-105397
https://issues.liferay.com/browse/LPS-105394

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/81687<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/6ae1850162ad~1...6ae1850162ad) <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
