### PR TITLE
LPS-126459, LPS-126259 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-126459
https://issues.liferay.com/browse/LPS-126259

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/david-gutierrez-mesa/liferay-portal/pull/66<br></br>

**Comment by austinchiang** [comment]
ci:help

**Pull request closed without merging**
