### PR TITLE
LPS-160773 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-160773

**Original Tests Distribution:**

<b style="font-weight:normal;" id="docs-internal-guid-0a370ed8-7fff-8a25-6605-2ca73dfff127"> 

Test File Name | Test counts
-- | --
KBAdmin | 33
KBDisplayWidget | 32
KBUsercase | 12
KBUpgeade | 3
KBWorkflow | 2
KBArticleWidget | 1
KBLocalization | 1
KBPermissions | 1
KBNotification | 1
Total | 86

</b>

**New Tests Distribution:**

<b style="font-weight:normal;" id="docs-internal-guid-0a370ed8-7fff-8a25-6605-2ca73dfff127"> 

Test File Name | Test counts
-- | --
KBAdmin | 6
KBArticle | 19
KBDisplayWidget | 26
KBUpgrade | 3
KBWorkflow | 3
KBArticleWidget | 1
KBLocalization | 1
KBPermissions | 1
KBNotification | 1
KBFolder | 5
KBTemplates | 3
KBExportImport | 3
KBSearch | 4
KBHierarchy | 9
Total | 85

</b>

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
Not ready to be reviewed.

/cc @austinchiang

**Comment by Jeremy-Ch** [comment]
ci:help

**Comment by Jeremy-Ch** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
@Jeremy-Ch 
- Make sure to update the test map
- We need a KBArticle.testcase

**Comment by Jeremy-Ch** [comment]
ci:test:knowledge-base

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
All knowledge base tests passed. https://testray.liferay.com/zh/home/-/testray/case_results?testrayBuildId=1949051362&testrayRunId=1949051406

**Comment by Jeremy-Ch** [comment]
Hi @austinchiang  Could you help to review this pull request first? If it doesn't need any update. Then I will update the test map. Thanks.

**Comment by Jeremy-Ch** [comment]
See new pull request https://github.com/austinchiang/liferay-portal/pull/1421

**Pull request closed without merging**
