### PR TITLE
LPS-147822 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-147822

Hi @austinchiang  I didn't write the curl part into a macro, because I think the macro can not be used for other tests. If you have any questions, please let me know. Thanks.

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/3298<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/22bbe74aad55~2...22bbe74aad55)

**Comment by austinchiang** [comment]
@Jeremy-Ch 
- We don't need every macro to be reusable. Even if it's only covering one test it's better for readability purposes
- This macro can be extended and reused anyway
- The tests passed on your local machine but I don't think localhost is going to work in CI tests https://github.com/liferay-lima/liferay-portal/pull/3298/commits/c0502b787a688a825f4ab16c0ccb5d40c6e492fd#diff-cda4e4fd78a004de194938984557753956a6b61a008905c53e5f04c436db8411L1176. I changed it and am testing it
- Don't add new tests to acceptance. Remember to look at the global property that's set in the file

**Pull request closed without merging**
