### PR TITLE
LPS-111251 Prevented key listener in source mode.

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey @austinchiang , there are still 3 tests failing for `ci:test:relevant`. The third one has a reference to _AlloyEditor_ that I guess needs to be updated. But for the first 2... could you please guide me and check if I have to fix something? Thanks a lot.

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/764<br></br>

**Pull request closed without merging**
