### PR TITLE
LRQA-36370 | master

### PR DESCRIPTION
**Pull request by john-fernandez**
https://issues.liferay.com/browse/LRQA-36370

### CODE REVIEW

**Comment by john-fernandez** [comment]
ci:test

**Comment by john-fernandez** [comment]
ci:test

**Comment by john-fernandez** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
No test changes needed

**Comment by austinchiang** [comment]
No test changes needed

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54038

**Pull request closed without merging**
