### PR TITLE
master-lps-129220

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-129216
https://issues.liferay.com/browse/LPS-129220

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Thanks for refactoring this @liuxingye !

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
@austinchiang Thank you for your introduction on equivalence partitioning.

**Pull request closed without merging**
