### PR TITLE
LPS-126455 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-126455

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Nice job @Hanlf

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1555<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/151b044eeb34~1...151b044eeb34)

**Pull request closed without merging**
