### PR TITLE
master-lps-131441

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
Hi @austinchiang , I have created some macros for the wiki JSON and they can be worked well on my local. I don't refactor any wiki tests to use JSON, I think that we can do it when refactoring the wiki tests. Could you help to review this pr when you have time? Thanks.
https://issues.liferay.com/browse/LPS-131441

How to use wiki JSON:
 ```
         JSONWiki.addWikiNode(
			groupName = "Guest",
			wikiNodeDescription = "Test Wiki Node Description",
			wikiNodeName = "Test Wiki Node Name");

		JSONWiki.addWikiPage(
			encodingFormat = "html",
			groupName = "Guest",
			tagName = "tag1",
			wikiNodeName = "Test Wiki Node Name",
			wikiPageContent = "Test Wiki Content",
			wikiPageName = "Test Wiki Page Name");

		JSONWiki.addAttachmentToWikiPage(
			fileName = "Document_1.jpg",
			groupName = "Guest",
			mimeType = "image/jpeg",
			wikiNodeName = "Test Wiki Node Name",
			wikiPageName = "Test Wiki Page Name");

		JSONWiki.addWikiChildPage(
			encodingFormat = "html",
			groupName = "Guest",
			tagName = "tag2",
			wikiChildPageContent = "Test Wiki Child Pag Content",
			wikiChildPageName = "Test Wiki Child Page Name",
			wikiNodeName = "Test Wiki Node Name",
			wikiParentPageName = "Test Wiki Page Name");

		JSONWiki.addAttachmentToWikiPage(
			fileName = "Document_1.doc",
			groupName = "Guest",
			mimeType = "application/msword",
			wikiNodeName = "Test Wiki Node Name",
			wikiPageName = "Test Wiki Child Page Name");
```

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Good work @Jeremy-Ch

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
