### PR TITLE
LPS-136783, LPS-136788, LPS-136809 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-136783
https://issues.liferay.com/browse/LPS-136788
https://issues.liferay.com/browse/LPS-136809

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
