### PR TITLE
LPS-102965 Add markup / styles to fit the design

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang !

We've made the following changes to the site navigation:
- Changed the icon from "site" to "change"
- Added the kind of group ("site" or "repository") on top of the group name.

In the ticket there's a link to a Figma design where you can see how this is supposed to look like (the design includes quite a lot more than the site navigation).

This will probably break some Poshi tests, as the markup is different and some literals have changed as well ("Go to Site" -> "Go to Space"). Let me know if you need anything here.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
Pushed back [here](https://github.com/adolfopa/liferay-portal/pull/1152)

**Pull request closed without merging**
