### PR TITLE
master-lps-124561_1

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-124561

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@Jeremy-Ch please rename your commits to use the story LPS not subtask so it's easier to search for later. Thx

**Comment by Jeremy-Ch** [comment]
See: https://github.com/austinchiang/liferay-portal/pull/1071

**Pull request closed without merging**
