### PR TITLE
LPS-136778, LPS-136954, LPS-142412 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-136778
https://issues.liferay.com/browse/LPS-136954
https://issues.liferay.com/browse/LPS-142412

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@liuxingye "redundant" means duplicate. In [this case](https://github.com/austinchiang/liferay-portal/pull/1167/commits/1e3f96af9a562b1ae2c63574668bb86c77bac418) there was no duplicate step so instead you can say "unnecessary", "extra" or "extraneous" steps

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2476

**Comment by liuxingye** [comment]
@austinchiang thanks for explaining me that.

**Pull request closed without merging**
