### PR TITLE
LRQA-38094 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-38094

### CODE REVIEW

**Comment by austinchiang** [comment]
Hey @john-co, can you take out the `|` in your commit message? Thanks!

**Comment by john-co** [comment]
@austinchiang, done. Thanks!

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
Pushed to AChu.
https://github.com/anthony-chu/liferay-portal/pull/326

**Pull request closed without merging**
