### PR TITLE
master-lps-102472

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-106172
https://issues.liferay.com/browse/LPS-106173
https://issues.liferay.com/browse/LPS-106175

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
Will review this with Jeremy's pull

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/665<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/f9c0d285f897~3...f9c0d285f897)

**Pull request closed without merging**
