### PR TITLE
master-lps-100462

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-100462

Send Poshi new case 1 and 2.

Thanks!

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
No changes.

**Comment by liuxingye** [comment]
ci:reopen

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78984

**Pull request closed without merging**
