### PR TITLE
Master | LRQA-53065, LRQA-54426, LPS-104328

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-53065
https://issues.liferay.com/browse/LRQA-54426
https://issues.liferay.com/browse/LPS-104328

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82090<br></br> <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
