### PR TITLE
LRQA-35985 | Master

### PR DESCRIPTION
**Pull request by acbbennett**
https://issues.liferay.com/browse/LRQA-35985

### CODE REVIEW

**Comment by acbbennett** [comment]
Per our discussion and comment on #257, I linked the macro change up to the testcase level. Per Patricia I did not add any changes to CP tests because there's a slightly different macro arrangement, but I confirmed that the paths will work should we want to update those in the future. Lemme know what you think.

**Comment by austinchiang** [comment]
No test changes needed.

**Comment by austinchiang** [comment]
@acbbennett Does this need to be applied to 7.0.x as well?

**Comment by acbbennett** [comment]
@austinchiang  this does not need to be applied to 7.0.x; the Document Type information is not present there.

**Pull request closed without merging**
