### PR TITLE
master-lps-105622

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-105622

@austinchiang I've automated "**workspace breadcrumb from inside web content field**" via view a depot wc content on a connected site.

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82016<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/6aedd2fd695b~2...6aedd2fd695b) <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
@liuxingye The goal of this test is to validate that repositories can be accessed through the web content field. We already have tests validating web content in depots so we don't need to test that further.

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/82018<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/b208230432a8~1...b208230432a8) <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
