### PR TITLE
Master | LPS-83411, LRQA-51424, LRQA-51527, LRQA-51529

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-83411
https://issues.liferay.com/browse/LRQA-51424
https://issues.liferay.com/browse/LRQA-51527
https://issues.liferay.com/browse/LRQA-51529

For LPS-83411, 
Still has some issue when adding Excel via OneDriver editor, confirming with @cgoncas.
After LRCI-558 is done, the new tests will run as expected on jenkins.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:onlineediting

**Comment by Hanlf** [comment]
ci:test:documents

**Comment by Hanlf** [comment]
Check the CI result, he above failures are not related to my pull.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77255

**Pull request closed without merging**
