### PR TITLE
Master | LPS-104258

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-104258

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/austinchiang/liferay-portal/pull/735<br></br>

**Comment by austinchiang** [comment]
See changes [here](https://github.com/austinchiang/liferay-portal/pull/735/commits/d8cba5ae88b342ac2801a78dd97f94ba3394b983)

**Pull request closed without merging**
