### PR TITLE
LRQA-31778, LRQA-33316, LRQA-33428, LRQA-33625, LRQA-33916 | ee-7.0.x

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-31778
https://issues.liferay.com/browse/LRQA-33316
https://issues.liferay.com/browse/LRQA-33428
https://issues.liferay.com/browse/LRQA-33625
https://issues.liferay.com/browse/LRQA-33916

@austinchiang this is a forward-port for tests added in legacy branches that also apply to master - especially the Training department tests.  Thanks!  (fyi, I usually send this to Anthony, so I can wait until he's back then send it to him, if you don't have the bandwidth for it.)

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
@brianwulbern sounds good, I'll take a look at it. Thanks!

**Comment by austinchiang** [comment]
Hey @brianwulbern @frankfu926 I'm gonna add some negative assertions after removing a portlet in https://github.com/austinchiang/liferay-portal/pull/140/commits/45c4d54f38a809ebe9ea43439e53908b948617a3, but I will do that (here)[https://issues.liferay.com/browse/LRQA-34475] after this pull gets merged in master. Let me know if you have any questions!

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/50956

**Comment by brianwulbern** [comment]
Ah, good idea @austinchiang, thanks for spotting that.

**Pull request closed without merging**
