### PR TITLE
master-qa-97041

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-97041

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Hey @liuxingye, we shouldn't be hardcoding paths into testcases. I'll push this in for now, but please file a **Test Improvement** ticket and create a locator for these path(s). Thanks!

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/75822

**Comment by liuxingye** [comment]
Hi @austinchiang, I'm referring to this [line](https://github.com/brianchandotcom/liferay-portal-ee/blame/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/assetsharing/DMSharing.testcase#L284) to write the coding locator, but I've already fixed them in the following pull.
https://github.com/brianchandotcom/liferay-portal/pull/75918
Thank you for the reminder.

**Pull request closed without merging**
