### PR TITLE
master-lps-132383_5

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-130238

<div class="user-content-block" style="margin: 0px; padding: 0px; overflow: auto hidden; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="table-wrap" style="margin: 0px; padding: 0px;">
Test File Name | Refactorneeded | New add or spilt | Removed | Move in | Move out | Total (Refactordone) | Comment
-- | -- | -- | -- | -- | -- | -- | --
CPWiki.testcase | 13 | &nbsp; | 1 | 1 | &nbsp; | 13 | Remove test&nbsp;CKEditorSmoke
PGWiki.testcase | 27 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | 27 | &nbsp;
WikiUsecase.testcase | 10 | &nbsp; | 1 | &nbsp; | 2 | 7 | - Move test RestoreDeletedFrontPage to CPWiki.testcase and rename to CanViewRestoreFrontPage&nbsp;- Move test CanViewAttachmentAfterPublishingto stagingWiki.testcase
StagingWiki.testcase | 3 | 2 | &nbsp; | 1 | &nbsp; | 6 | Split test AddWikiAndCreateContentWithStagingThenPublishAfterDelete to three tests: * StagingWiki#CanViewWikiPageAfterPublishingStagingWiki#CanViewFrontPageAfterPublishingStagingWiki#CannotViewDeletedWikiPageAfterPublishing
PGWikidisplay.testcase | 5 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | 5 | &nbsp;
CPRolesCPWiki.testcase | 2 | 2 | &nbsp; | &nbsp; | &nbsp; | 4 | Add 2 new tests （Validate the wiki node and page can CED with permissions）：CanEditAndDeleteWikiNodeWithPermissionsCanEditAndDeleteWikiPageWithPermissions
Total | 60 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | 62 | &nbsp;

</div></div><br class="Apple-interchange-newline">

NOTE:

- Found a bug [LPS-133167](https://issues.liferay.com/browse/LPS-133167) when refactoring the test, I will fix it on [LPS-134272](https://issues.liferay.com/browse/LPS-134272).
- Please don't remove some navigation step before `JSONWiki.updateWikiPage`, the step is used for loading the wiki node after adding a new site or instance.

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
Not ready for reviewing.

/cc @austinchiang

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:wiki

**Comment by Jeremy-Ch** [comment]
Ready for reviewing.

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/liferay-lima/liferay-portal/pull/1954<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/a6829fec7859~7...a6829fec7859)

**Comment by austinchiang** [comment]
Good job @Jeremy-Ch , I'm not going to remove the @refactordone added to new tests since they were created in the context of refactoring.

**Pull request closed without merging**
