### PR TITLE
LPS-103698 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @austinchiang 

Just checking that this fixes 2 poshi tests. Let me know if there's something missing.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/81546<br></br> <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
