### PR TITLE
master-lrqa-58630

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-58630

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Pushed here: https://github.com/liferay-lima/liferay-portal/pull/75

@liuxingye please see https://github.com/liferay-lima/liferay-portal/pull/75/commits/838037fec4a2ea578426f513a0453fb240acf5a2

**Comment by liuxingye** [comment]
Noticed your changes, thanks @austinchiang

**Pull request closed without merging**
