### PR TITLE
LPS-145209, LPS-145529, LPS-146528 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-145209
https://issues.liferay.com/browse/LPS-145529
https://issues.liferay.com/browse/LPS-146528

@austinchiang in case of conflict, sent my commits along with @Jeremy-Ch [commits ](https://github.com/Hanlf/liferay-portal/pull/345) together

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
