### PR TITLE
LPS-100926 TEST Get google drive credential in integration test

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LPS-100926

If this works you will have to check it with the individuals who manage portal-impl/test/portal-test-ext.properties, /portal-kernel/src/com/liferay/portal/kernel/util/PropsKeys.java and /portal-impl/src/com/liferay/portal/util/PropsValues.java.

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:onlineediting

**Comment by yichenroy** [comment]
ci:test:onlineediting

**Comment by yichenroy** [comment]
ci:test:onlineediting

**Comment by 4lejandrito** [comment]
Hi @yichenroy,

Thanks for looking into this. Two things:

1. I don't think adding the keys to `PropsKeys` and `PropsValues` is necessary since those keys are only meant to exist in a test environment. It is ok to leave them hardcoded in the tests.
2. Can we get access to the generated `portal-test-ext.properties` to see whether or not our values are there?

Regards

**Comment by yichenroy** [comment]
Hi @4lejandrito 
1. Sounds good 
2. If you search for `portal-test-ext.properties` in the console log https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/339598/consoleFull and you will see the values for this file printed, it looks like the values weren't being read/written correctly: 
`google.drive.integration.client.id.1=${google.drive.integration.client.id.1}`

**Pull request closed without merging**
