### PR TITLE
LPS-139277 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-139277

Refactor the depot staging tests.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Nice work @Hanlf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
