### PR TITLE
master-lps-102542

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-104612
https://issues.liferay.com/browse/LPS-104614
https://issues.liferay.com/browse/LPS-104653
https://issues.liferay.com/browse/LPS-104654
https://issues.liferay.com/browse/LPS-104655
https://issues.liferay.com/browse/LPS-104657

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
'Just <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
'Just <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81102

**Pull request closed without merging**
