### PR TITLE
Master | LPS-105582

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-105582

@austinchiang Since Beck's commits about this story haven't merged into upstream, I pull my commits with his pull together.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
Hi @austinchiang  I have completed the rest tests and submitted base on this pull request, please close it and see https://github.com/austinchiang/liferay-portal/pull/690

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Pull request closed without merging**
