### PR TITLE
master-lps-122849

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-122849

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@liuxingye getting some merge conflicts. Can you please rebase and resend? Thx

**Comment by liuxingye** [comment]
@austinchiang sure, please see https://github.com/austinchiang/liferay-portal/pull/881.

**Pull request closed without merging**
