### PR TITLE
Master | LRQA-39854

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-39854

7.2.x here: https://github.com/austinchiang/liferay-portal-ee/pull/234

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:messageboards

**Comment by Hanlf** [comment]
ci:test:messageboards

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/80495

**Pull request closed without merging**
