### PR TITLE
Master | LPS-106488

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-106488

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:help

**Comment by austinchiang** [comment]
@Hanlf can you rebase and resend? Thx

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
**Pull request submitted:** https://github.com/brianchandotcom/liferay-portal/pull/85180<br></br>Please see changes [here.](https://github.com/austinchiang/liferay-portal/compare/9e3f1496ab59~1...9e3f1496ab59)

**Comment by Hanlf** [comment]
sorry @austinchiang , I missed your comment above, just saw...

**Pull request closed without merging**
