### PR TITLE
LRQA-49142 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-49142

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77957

@liuxingye @Jeremy-Ch  I decided to keep [this path](https://github.com/austinchiang/liferay-portal/pull/470/commits/3093cfc370ca754bad086c2c92fb29d0100c1f77#diff-4e143a06432b5d90445c799ee660a8d0R143). The CKEditor path is too general and will only work for jpg images. Having this path should allow for more flexibility in case we want to write more coverage for this in the future.

**Comment by liuxingye** [comment]
@austinchiang  Got it. Thanks.

**Pull request closed without merging**
