### PR TITLE
Master | LPS-101741

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-101741

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
@austinchiang  The above SF issue is not related to my pull, will fix it under https://issues.liferay.com/browse/LRQA-57071

**Comment by Hanlf** [comment]
SF passes with the SF fix commit: https://github.com/Hanlf/liferay-portal/pull/112#issuecomment-603131175

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Will review in https://github.com/austinchiang/liferay-portal/pull/720

**Pull request closed without merging**
